const fs=require('fs'), path=require('path');
const root=__dirname, out=path.join(root,'dist');
function rm(p){if(fs.existsSync(p)) fs.rmSync(p,{recursive:true,force:true})}
rm(out); fs.mkdirSync(out,{recursive:true}); fs.mkdirSync(path.join(out,'blog'),{recursive:true});
function readJSON(f){return JSON.parse(fs.readFileSync(path.join(root,f),'utf8'))}
function esc(s=''){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function md(s=''){
  return s.replace(/\r/g,'').split(/\n\n+/).map(block=>{
    block=block.trim(); if(!block)return '';
    if(block.startsWith('### ')) return '<h3>'+inline(block.slice(4))+'</h3>';
    if(block.startsWith('## ')) return '<h2>'+inline(block.slice(3))+'</h2>';
    if(block.startsWith('# ')) return '<h1>'+inline(block.slice(2))+'</h1>';
    if(block.startsWith('> ')) return '<div class="quote">'+inline(block.replace(/^> /,''))+'</div>';
    if(block.split('\n').every(x=>/^[-*] /.test(x))) return '<ul>'+block.split('\n').map(x=>'<li>'+inline(x.slice(2))+'</li>').join('')+'</ul>';
    return '<p>'+inline(block).replace(/\n/g,'<br>')+'</p>';
  }).join('');
}
function inline(s){return esc(s).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\*(.+?)\*/g,'<em>$1</em>').replace(/\[(.+?)\]\((https?:\/\/[^)]+)\)/g,'<a href="$2" target="_blank" rel="noopener">$1</a>')}
function materialCard(m){if(!m)return ''; const image=m.image?`<img class="material-image" src="${esc(m.image)}" alt="${esc(m.image_alt||m.title||'')}">`:''; const doc=m.document_url?`<a class="material-link" href="${esc(m.document_url)}" target="_blank" rel="noopener">📎 ${esc(m.document_label||'Открыть документ')}</a>`:''; return `<article class="material-card">${image}<div class="material-content">${m.date?`<div class="post-date">${esc(m.date)}</div>`:''}${m.title?`<h3>${esc(m.title)}</h3>`:''}${m.text?`<div class="material-text">${md(m.text)}</div>`:''}${doc}</div></article>`;}
function materialsBlock(items,title='Материалы'){if(!items||!items.length)return ''; return `<section class="materials-section"><h2>${esc(title)}</h2><div class="materials-grid">${items.map(materialCard).join('')}</div></section>`;}
const pages=readJSON('content/pages.json');
const site=readJSON('content/site.json');
const nav=(site.nav||[['index.html','Главная'],['about.html','Обо мне'],['colleagues.html','Коллегам'],['parents.html','Родителям'],['children.html','Дети'],['environment.html','Среда'],['portfolio.html','Портфолио'],['blog.html','Блог']]).map(x=>Array.isArray(x)?x:[x.link,x.label]);
function layout(title,desc,body,current='',image=''){
 const canonicalBase=(site.site_url||'https://example.com').replace(/\/$/,''); const canonical=canonicalBase+'/'+(current||'index.html');
 const person=JSON.stringify({"@context":"https://schema.org","@type":"Person",name:site.name,jobTitle:site.tagline,description:desc,url:canonical,image:image||undefined}).replace(/,\"image\":undefined/,'');
 return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><meta name="keywords" content="${esc(site.site_keywords||'дошкольное образование, воспитатель, педагогическое портфолио, Челябинск, Южный Урал') }"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${esc(canonical)}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}">${image?`<meta property="og:image" content="${esc(image)}">`:''}<link rel="stylesheet" href="/styles.css"><link rel="icon" href="data:,"><script type="application/ld+json">${person}</script></head><body><header class="header"><div class="wrap"><a class="brand" href="/index.html"><span class="mark">А</span><span><b>${esc(site.name)}</b><small>${esc(site.tagline)}</small></span></a><button class="menu-toggle" aria-label="Меню">☰</button><nav class="nav">${nav.map(([u,n])=>`<a class="${current===u?'active':''}" href="/${u}">${n}</a>`).join('')}</nav></div></header>${body}<footer class="footer"><div class="wrap">${esc(site.footer)}</div></footer><script src="/script.js"></script></body></html>`}
function hero(label,title,intro){return `<section class="page-hero"><div class="wrap"><div class="breadcrumbs"><a href="/index.html">Главная</a> → ${esc(label)}</div><h1>${esc(title)}</h1><p>${esc(intro)}</p></div></section>`}
function save(name,html){fs.writeFileSync(path.join(out,name),html)}
// copy static assets
for(const f of ['styles.css','script.js','robots.txt']) fs.copyFileSync(path.join(root,f),path.join(out,f)); fs.cpSync(path.join(root,'admin'),path.join(out,'admin'),{recursive:true});
fs.mkdirSync(path.join(out,'images'),{recursive:true});
if(fs.existsSync(path.join(root,'static/images/uploads'))) fs.cpSync(path.join(root,'static/images/uploads'),path.join(out,'images/uploads'),{recursive:true});
// Home
let h=`<main><section class="hero"><div class="wrap hero-grid"><div><div class="eyebrow">Педагогическое портфолио · Южный Урал</div><h1>${esc(site.home_title)}</h1><p class="lead">${md(site.home_intro)}</p><div class="hero-actions"><a class="button" href="/about.html">${esc(site.home_about_button_label||'Познакомиться')}</a><a class="button ghost" href="/blog.html">${esc(site.home_blog_button_label||'Блог')}</a><a class="button ghost" href="/portfolio.html">${esc(site.home_portfolio_button_label||'Портфолио')}</a></div></div><div class="hero-card hero-photo-card">${site.home_photo?`<img class="educator-photo" src="${esc(site.home_photo)}" alt="${esc(site.home_photo_alt||site.name)}">`:''}<div class="sun">✦</div><h3>${esc(site.home_card_title)}</h3><p>${md(site.home_card_text)}</p></div></div></section><section class="content"><div class="wrap prose"><div class="section-kicker">Педагогическая философия</div><h2>${esc(site.philosophy_title)}</h2><div>${md(site.philosophy_text)}</div><div class="quote">${esc(site.quote)}</div><div class="cards">${pages.cards.map(c=>`<a class="card" href="/${c.link}"><span>${esc(c.kicker)}</span><h3>${esc(c.title)}</h3><div>${md(c.text)}</div>${materialsBlock(c.materials,'Материалы')}</a>`).join('')}</div>${materialsBlock(site.home_materials,'Материалы на главной')}</div></section></main>`;
save('index.html',layout(site.home_title,site.home_description,h,'index.html'));
// pages
for(const p of pages.pages){const body=`<main>${hero(p.title,p.title,p.intro)}<section class="content"><div class="wrap prose">${p.cover_image?`<img class="page-cover" src="${esc(p.cover_image)}" alt="${esc(p.cover_image_alt||p.title)}">`:''}${md(p.body)}${p.tags?.length?`<div class="tag-row">${p.tags.map(t=>`<span class="pill">${esc(t)}</span>`).join('')}</div>`:''}${materialsBlock(p.materials,'Материалы раздела')}</div></section></main>`; save(p.slug+'.html',layout(p.title,p.description,body,p.slug+'.html'));}
// portfolio
const cards=pages.portfolio.map(a=>`<a class="card" href="/${a.slug}.html"><span>${esc(a.kicker)}</span><h3>${esc(a.title)}</h3><p>${esc(a.text)}</p></a>`).join('');
save('portfolio.html',layout('Портфолио — Анна Неволина','Педагогическое портфолио воспитателя детского сада: образование, повышение квалификации, достижения и достижения воспитанников.',`<main>${hero('Портфолио','Портфолио','Путь педагога — это не витрина, а следы роста, поиска и совместных открытий.')}<section class="content"><div class="wrap prose"><div class="cards">${cards}</div></div></section></main>`,'portfolio.html'));
for(const a of pages.portfolio){save(a.slug+'.html',layout(a.title,a.text,`<main>${hero('Портфолио',a.title,a.text)}<section class="content"><div class="wrap prose">${a.cover_image?`<img class="page-cover" src="${esc(a.cover_image)}" alt="${esc(a.cover_image_alt||a.title)}">`:''}<h2>${esc(a.gallery_title)}</h2><div>${md(a.gallery_text)}</div>${materialsBlock(a.materials,'Материалы раздела')}<a class="button" href="/admin/">Добавить материалы</a></div></section></main>`,'portfolio.html'));}
// blog
const postsDir=path.join(root,'content/posts'); let posts=[]; if(fs.existsSync(postsDir)) for(const f of fs.readdirSync(postsDir).filter(f=>f.endsWith('.md'))){const raw=fs.readFileSync(path.join(postsDir,f),'utf8'); const m=raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/); let meta={},body=''; if(m){m[1].split('\n').forEach(l=>{const x=l.match(/^([^:]+):\s*(.*)$/);if(x)meta[x[1].trim()]=x[2].trim().replace(/^['"]|['"]$/g,'')});body=m[2]} else body=raw; posts.push({...meta,body,slug:f.replace(/\.md$/,'')});}
posts.sort((a,b)=>(b.date||'').localeCompare(a.date||''));
const postCards=posts.length?posts.map(p=>`<article class="post-card"><div class="post-date">${esc(p.date||'')}</div><h2><a href="/blog/${esc(p.slug)}.html">${esc(p.title||p.slug)}</a></h2><p>${esc(p.description||'')}</p><a class="readmore" href="/blog/${esc(p.slug)}.html">Читать →</a></article>`).join(''):`<div class="empty-gallery"><h2>Блог только начинается</h2><p>Здесь будут появляться заметки о детях, родном крае, проектах и педагогических находках.</p><a class="button" href="/admin/">Создать первую публикацию</a></div>`;
save('blog.html',layout('Блог — Анна Неволина','Заметки воспитателя о дошкольном детстве, Южном Урале, краеведении и педагогике.',`<main>${hero('Блог','Блог','Место для живых заметок, проектов, фотографий и педагогических открытий.')}<section class="content"><div class="wrap post-list">${postCards}</div></section></main>`,'blog.html'));
for(const p of posts){save('blog/'+p.slug+'.html',layout(p.title||'Публикация',p.description||'',`<main>${hero('Блог',p.title||'',p.description||'')}<section class="content"><div class="wrap prose">${p.image?`<img class="post-image" src="${esc(p.image)}" alt="${esc(p.title||'')}">`:''}${md(p.body)}${p.document_url?`<p><a class="button" href="${esc(p.document_url)}" target="_blank" rel="noopener">📎 ${esc(p.document_label||'Открыть материал')}</a></p>`:''}${materialsBlock(p.materials,'Дополнительные материалы')}</div></section></main>`,'blog.html'));}
// sitemap
const base=(site.site_url||'https://example.com').replace(/\/$/,''); const urls=['/index.html',...(pages.pages||[]).map(x=>'/'+x.slug+'.html'),'/portfolio.html',...(pages.portfolio||[]).map(x=>'/'+x.slug+'.html'),'/blog.html',...posts.map(x=>'/blog/'+x.slug+'.html')]; const unique=[...new Set(urls)]; fs.writeFileSync(path.join(out,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+unique.map(u=>`<url><loc>${base}${u}</loc></url>`).join('')+'</urlset>');
